name: train_diabetes_model
display_name: Train Diabetes Model
# version: 1 # Not specifying a version will automatically update the version
type: command
inputs:
  training_data: 
    type: uri_folder
  reg_rate:
    type: number     
  registered_model_name:
    type: string
outputs:
  model:
    type: uri_folder
code: .
environment:
  azureml:mlflow-env:0.1.7
command: >-
  python train.py 
  --training_data ${{inputs.training_data}} 
  --reg_rate ${{inputs.reg_rate}}
  --registered_model_name ${{inputs.registered_model_name}} 
  --model ${{outputs.model}}